extends: airbnb
parserOptions:
  ecmaVersion: 2020
env:
  browser: true
rules:
  react/prop-types: 0
  object-curly-newline:
  - error
  - ObjectExpression:
      minProperties: 5
      multiline: true
      consistent: true
    ObjectPattern:
      minProperties: 5
      multiline: true
      consistent: true
    ImportDeclaration:
      minProperties: 4
      multiline: true
      consistent: true
    ExportDeclaration:
      minProperties: 4
      multiline: true
      consistent: true
  no-plusplus:
    - error
    - allowForLoopAfterthoughts:
        true
